Issue-3: Added strict checks. Added tests.

diff --git a/wb b/wb
--- a/wb
+++ b/wb
@@ -78,24 +78,35 @@ _wb_check_valid_abspath () {
     fi
 }
 _wb_print_path_if_child () {
-    realpath --help 2&>1 > /dev/null
-    if [[ $? -eq 0 ]] && [[ -z "${WORKBENCH_ALLOW_INSECURE_PATH}" ]]; then
-        local ret
-        local toCheck="$(_wb_realpath $1)"
-        local prefix="$(_wb_realpath $2)"
-        _wb_check_valid_abspath "$toCheck"
-        ret=$?
-        [[ $ret -ne 0 ]] && return $ret
-        _wb_check_valid_abspath "$prefix"
-        ret=$?
-        [[ $ret -ne 0 ]] && return $ret
-        local prefixLen=${#prefix}
-        local toCheckPrefix="${toCheck:0:$prefixLen}"
-        if [[ "$toCheckPrefix" != "$prefix" ]]; then
-            err "Item '${toCheck}' lies outside '${prefix}'. Disallowed."
-            return $ERR_INVALID
+    if [[ -z "${WORKBENCH_ALLOW_INSECURE_PATH}" ]]; then
+        realpath --help 2&>1 > /dev/null
+        if [[ $? -eq 0 ]]; then
+            local ret
+            local toCheck="$(_wb_realpath $1)"
+            local prefix="$(_wb_realpath $2)"
+            _wb_check_valid_abspath "$toCheck"
+            ret=$?
+            [[ $ret -ne 0 ]] && return $ret
+            _wb_check_valid_abspath "$prefix"
+            ret=$?
+            [[ $ret -ne 0 ]] && return $ret
+            local prefixLen=${#prefix}
+            local toCheckPrefix="${toCheck:0:$prefixLen}"
+            if [[ "$toCheckPrefix" != "$prefix" ]]; then
+                err "Item '${toCheck}' lies outside '${prefix}'. Disallowed."
+                return $ERR_INVALID
+            fi
+            echo "${toCheck}"
+        else
+            #   This is a strict check on each call: `_wb_print_path_if_child`
+            #   A similar check is done using `_wb_check_realpath` on launch
+            #   for convenience. But it could be bypassed.
+            err "FATAL: 'realpath' not found. Can't compose absolute paths."
+            err "       WORKBENCH_ALLOW_INSECURE_PATH not set either."
+            exit $ERR_FATAL
         fi
-        echo "${toCheck}"
+    else
+        echo "$1"
     fi
 }
 
